##  LAB 1-1

In [1]:
import numpy as np
# Take dimensions & Data
N, M = map(int, input().split())
A = np.array([list(map(int, input().split())) for i in range(N)])
B = np.array([list(map(int, input().split())) for i in range(N)])
#Make our operations
add = A + B
subtract = A - B
multipl = A * B
div = np.floor_divide(A, B)
modulus = A % B
power = A ** B
# Get the results
print(add)
print(subtract)
print(multipl)
print(div)
print(modulus)
print(power)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## LAB 2-1

In [4]:
# Take dimensions & Data
N, M = map(int, input().split())
matrix = np.array([list(map(int, input().split())) for i in range(N)])

# transpose
transpose = np.transpose(matrix)

#  flattened array
flatten = matrix.flatten()
print("Transposed array : ")
print(transpose)
print("Flatten array : ")
print(flatten)

2 2 
1 2
3 4
Transposed array : 
[[1 3]
 [2 4]]
Flatten array : 
[1 2 3 4]


## LAB 3-1

In [5]:
# Take dimensions & Data
N, M = map(int, input().split())
matrix = np.array([list(map(int, input().split())) for _ in range(N)])

# Compute the mean 
mean = np.mean(matrix, axis=1)
# Compute the variance 
var = np.var(matrix, axis=0)
# Compute the standard deviation along the entire array
std = np.std(matrix, axis=None)

# Print the results
print(mean)
print(var)
print(std)


2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


## LAB 4-1

In [6]:
coefficients = list(map(float, input().split()))
x = float(input())
result = np.polyval(coefficients, x)
print(result)

1.1 2 3
0
3.0


## LAB 5-1

In [8]:
# Creat 3D Array
random_array = np.random.rand(3, 3)
# Get first two rows
two_rows = random_array[:2]
# Get first two column
first_column = random_array[:, 0]
# Get second element third row
second_element_third_row = random_array[2, 1]
print("First two rows:")
print(two_rows)
print("\nFirst column:")
print(first_column)
print("\nSecond element of the third row:", second_element_third_row)


First two rows:
[[0.44091073 0.69109362 0.18131267]
 [0.66710747 0.0875695  0.23612429]]

First column:
[0.44091073 0.66710747 0.43774096]

Second element of the third row: 0.504330497664742


## LAB 6-1

In [11]:
#  Add a Shipping Fee
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
total = prices + 5
# Create a Random Discount Array
rng = np.random.default_rng(2022)
random_array = rng.random(size=9).reshape(3, 3)
# Apply Discounts to Prices
discount = random_array[:2].flatten()
pct_owed = 1 - discount
final_owed = np.round(pct_owed * total, 2)

print("Discount Percentage Array:")
print(discount)
print("Percentage Owed After Discount:")
print(pct_owed)
print("Final Amount Owed After Discount:")
print(final_owed)


Discount Percentage Array:
[0.24742606 0.09299006 0.61176337 0.06066207 0.66103343 0.75515778]
Percentage Owed After Discount:
[0.75257394 0.90700994 0.38823663 0.93933793 0.33896657 0.24484222]
Final Amount Owed After Discount:
[ 8.27 10.88 10.67 98.62  3.39 13.46]
